# Generated by Django 2.2.12 on 2020-06-03 10:31

from django.db import migrations, models
import djongo.models.fields
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', djongo.models.fields.ArrayField(model_container=recipes.models.LangText)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
