# Generated by Django 2.2.12 on 2020-06-09 14:47

from django.db import migrations, models
import djongo.models.fields
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200603_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lang', models.CharField(max_length=256)),
                ('ingredients', djongo.models.fields.ArrayField(model_container=recipes.models.IngredientItem, model_form_class=recipes.models.IngredientItemForm)),
                ('categories', djongo.models.fields.ArrayField(model_container=recipes.models.Category)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=256)),
                ('video', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('tags', djongo.models.fields.ArrayField(model_container=recipes.models.ListText)),
            ],
        ),
    ]
